=== g-wong/XMLSurface/XMLSurface/default.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="GalleryFrame">
  <xs:complexType>
    <xs:sequence>
      <xs:element type="xs:string" name="Title"/>
      <xs:element type="xs:string" name="Type"/>
      <xs:element name="GalleryItems">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="GalleryItem" maxOccurs="unbounded" minOccurs="1">
              <xs:complexType>
                <xs:sequence>
                  <xs:element type="xs:anyURI" name="Image"/>
                  <xs:element type="xs:anyURI" name="Link"/>
                  <xs:element type="xs:boolean" name="NewWindow" minOccurs="0"/>
                  <xs:element type="xs:string" name="Title"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="DataFrame">
  <xs:complexType>
    <xs:sequence>
      <xs:element type="xs:string" name="Title"/>
      <xs:element type="xs:string" name="Type"/>
      <xs:element name="ImagePaths">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="xs:anyURI" name="string" maxOccurs="unbounded" minOccurs="1"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="VideoFrame">
  <xs:complexType>
    <xs:sequence>
      <xs:element type="xs:string" name="Title"/>
      <xs:element type="xs:string" name="Type"/>
      <xs:element type="xs:boolean" name="NewWindow" minOccurs="0"/>
      <xs:element type="xs:anyURI" name="VideoPath"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="GameFrame">
  <xs:complexType>
    <xs:sequence>
      <xs:element type="xs:string" name="Title"/>
      <xs:element type="xs:string" name="Type"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="InteractiveTourFrame ">
  <xs:complexType>
    <xs:sequence>
      <xs:element type="xs:string" name="Title"/>
      <xs:element type="xs:string" name="Type"/>
      <xs:element name="ImagePaths">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="xs:anyURI" name="string" maxOccurs="unbounded" minOccurs="1"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>


</xs:schema>

=== g-wong/XMLSurface/XMLSurface/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<GalleryFrame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/Users/santiago/XMLSurface/XMLSurface/default.xsd">
    <Title>Test1</Title>
    <Type>Test2</Type>
    <GalleryItems>
        <GalleryItem>
            <Image>/Users/santiago/contestapplet.conf</Image>
            <Link>Link</Link>
            <Title>asdad</Title>
            <NewWindow>false</NewWindow>
        </GalleryItem>
    </GalleryItems>
</GalleryFrame>
